apiVersion: v1
kind: Service
metadata:
  name: app-stationski
  labels:
    app: app-stationski
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: app-stationski
  type: ClusterIP
