apiVersion: v1
kind: Service
metadata:
  name: app-stationski
  labels:
    app: app-stationski
spec:
  ports:
    - name: http       # Add a unique name for this port
      port: 8089       # The port exposed by the service
      targetPort: 8089 # The container port that the service directs to
  selector:
    app: app-stationski
  type: ClusterIP
