apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stationski
  labels:
    app: app-stationski
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-stationski
  template:
    metadata:
      labels:
        app: app-stationski
    spec:
      containers:
        - name: app-stationski
          image: 192.168.80.142:5000/stationski:latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
                  "spring.datasource.username" : "root",
                  "spring.datasource.password" : "root",
                  "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                  "spring.jpa.hibernate.ddl-auto" : "update"
                }
